services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: profile
      POSTGRES_PASSWORD: profile
      POSTGRES_DB: profile_service
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  opensearch:
    image: opensearchproject/opensearch:2.19.0
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  localstack:
    image: localstack/localstack:4.4.0
    environment:
      SERVICES: sns,sqs
      DEBUG: 0
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    ports:
      - "4567:4566"
    volumes:
      - ./scripts/localstack-init.sh:/etc/localstack/init/ready.d/init.sh

volumes:
  postgres_data:
  opensearch_data:
